language: c

os:
    - linux
    - osx

sudo: false

env:
    # CONDA_JWST_DEPENDENCIES is used because CONDA_DEPENDENCIES is not truly global.
    global:
        - MAIN_CMD='python setup.py'
        - CONDA_CHANNELS='http://ssb.stsci.edu/conda-dev http://ssb.stsci.edu/astroconda'
        - CONDA_DEPENDENCIES='pytest jwst sphinx=1.3.5 qt=4 nose lxml requests fitsverify lockfile'
        - CONDA_JWST_DEPENDENCIES='pytest stsci-jwst sphinx=1.3.5 nose lxml requests fitsverify lockfile'
        - PIP_DEPENDENCIES='parsley coveralls'
        - CRDS_SERVER_URL='https://hst-crds.stsci.edu'
        - CRDS_TEST_ROOT=/tmp

    matrix:
        - PYTHON_VERSION=2.7
        - PYTHON_VERSION=3.5

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
    - ./setup_test_cache $CRDS_TEST_ROOT

script:
    - ./install
    - ./runtests --cover

# after_success:
#     coveralls
